### ISSUE TITLE
Patterns 

### ISSUE THREAD

**Issue by aaryadev** [azeemhassni/validator#2]
Very nice code 
 But..
- switching the validation type will be lengthy.
- repeated code pattern.
- non-global class name (personalized class name -> most people will either change or ignore the  repo )
  
  well as dennis said you can use this 

https://github.com/wwphp-fb/php-resources/blob/master/faq/oop/design-patterns/strategy.md

**Comment by azeemhassni** [comment]
Thanks @aaryadev  for your great feedback . 
please review https://github.com/azeemhassni/validator/tree/v2.0 this branch and than i will marge this to master
