### ISSUE TITLE
min and max validation didn't work

### ISSUE THREAD

**Issue by mbrinkme** [azeemhassni/validator#8]
Hallo!

Thank you for you validator. But min und max rules work not properly.

This Error Message "Firstname must be less than [10] characters" appears.

It doesn't matter how long my string ist. Less oder more than 10 Characters. Everytime the same error. The min:[2] parameter works not at all.

Here my rules:
$rules = array(  
 'firstname' => 'max:[10]|required',  
 'lastname' => 'min:[2]|required',  
);

Can you help me?

Greetings Marco

**Comment by mbrinkme** [comment]
I look at your code and understand now. The documentation wasn't clear for me. Now it works. 

$rules = array(
  'firstname' => 'max:10|required',
  'lastname' => 'min:2|required',
);

**Comment by azeemhassni** [comment]
@mbrinkme sorry for the late reply.

this is the correct syntax for min and max rules.

``` php
$rules = array(
  'firstname' => 'max:10|required',
  'lastname' => 'min:2|required',
);
```

I fixed that in docs BTW. now its clear?

**Comment by mbrinkme** [comment]
Now it's clear. Thanks!
